// ── POM Gebouw Opties Catalogus ───────────────────────────────────────────────
//
// Alle gebouwtypologieën zijn gegroepeerd in thematische sets.
// Groepsgrootte varieert van 2 tot 8 opties per groep.
//
// Afbeeldingen: src/assets/mass pictures/V1.png  (V1)
//               src/assets/mass pictures/v2.png  (v2)
//               src/assets/mass pictures/v3.png  (v3)
//
// Exporteert:
//   window.GEBOUW_OPTIES_GROUPS   – array van groepen (elk met .opties[])
//   window.GEBOUW_ALLE_OPTIES     – platte array voor snelle id-lookup

const _IMG = {
  v1: 'src/assets/mass pictures/V1.png',
  v2: 'src/assets/mass pictures/v2.png',
  v3: 'src/assets/mass pictures/v3.png',
};

const _IMG_floorplan = {
  v1: 'src/assets/mass pictures/floorplans/V1.jpg',
  v2: 'src/assets/mass pictures/floorplans/V2.jpg',
  v3: 'src/assets/mass pictures/floorplans/V3.jpg',
};


// ─────────────────────────────────────────────────────────────────────────────
//  Helper: ambitie scores als percentages (0–100)
// ─────────────────────────────────────────────────────────────────────────────
function _scores(gz, du, ad, vi, di) {
  return { gezondSchool: gz, duurzameSchool: du, adaptieveSchool: ad, veiligSchool: vi, digitaleSchool: di };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Groepen & opties
// ─────────────────────────────────────────────────────────────────────────────
window.GEBOUW_OPTIES_GROUPS = [

  // ── Groep 1: Grondgebonden (4 opties) ─────────────────────────────────────
  {
    id:          'grondgebonden',
    naam:        'Grondgebonden',
    kleur:       '#7C3AED',
    beschrijving: 'Eenlaagse of tweelaagse schoolgebouwen die breed op het kavel staan. Optimale daglicht­toetreding en directe aansluiting op buitenruimtes.',
    opties: [
      {
        id:           'compact',
        naam:         'Compact type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        2,
        bvo:          2500,
        footprint:    1350,
        bouwkosten:   6250000,
        tco:          13750000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Hoog',
        beschrijving: 'Compacte schoolvorm met efficiënte ruimtebenutting op twee bouwlagen. Geschikt voor kleinere kavels met beperkt bouwvlak.',
        eigenschappen: ['Kleine footprint', 'Efficiënt', 'Snel te realiseren'],
        ambitieScores: _scores(67, 55, 67, 75, 65),
      },
      {
        id:           'lineair',
        naam:         'Lineair type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        2,
        bvo:          2800,
        footprint:    1500,
        bouwkosten:   7000000,
        tco:          15400000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Hoog',
        beschrijving: 'Langgerekte plattegrond langs de straatrooilijn. Optimale daglichttoetreding aan beide zijden, heldere circulatie.',
        eigenschappen: ['Optimaal daglicht', 'Duidelijke routing', 'Goed aanpasbaar'],
        ambitieScores: _scores(80, 67, 70, 70, 67),
      },
      {
        id:           'cluster',
        naam:         'Cluster type',
        afbeelding:   _IMG.v3,
        afbeelding_floorplan:   _IMG_floorplan.v3,
        lagen:        2,
        bvo:          3100,
        footprint:    1700,
        bouwkosten:   7750000,
        tco:          17050000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Groepering van functies rondom een centraal ontmoetingshart. Stimuleert informele contacten en gemeenschapsgevoel.',
        eigenschappen: ['Centraal hart', 'Ontmoetingsgericht', 'Flexibele clusters'],
        ambitieScores: _scores(70, 75, 80, 67, 70),
      },
      {
        id:           'hof',
        naam:         'Hof type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        2,
        bvo:          3400,
        footprint:    2100,
        bouwkosten:   8500000,
        tco:          18700000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Laag',
        beschrijving: 'Gesloten bouwvorm rondom een beschut binnenhof. Geborgen buitenruimte voor kinderen, duidelijke scheiding publiek/privé.',
        eigenschappen: ['Binnenhof', 'Veilige buitenruimte', 'Representatief'],
        ambitieScores: _scores(67, 60, 55, 85, 62),
      },
    ],
  },

  // ── Groep 2: Gestapeld (3 opties) ─────────────────────────────────────────
  {
    id:          'gestapeld',
    naam:        'Gestapeld',
    kleur:       '#0D9488',
    beschrijving: 'Schoolgebouwen over drie of meer bouwlagen. Maximale benutting van een beperkt bouwvlak, met vertikale organisatie van functies.',
    opties: [
      {
        id:           'toren',
        naam:         'Toren type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        4,
        bvo:          2200,
        footprint:    600,
        bouwkosten:   5500000,
        tco:          12100000,
        duurzaamheid: 'Laag',
        maakbaarheid: 'Laag',
        beschrijving: 'Meerdere bouwlagen op een kleine footprint. Ideaal bij sterk beperkt kavelbegrip of midden in stedelijk weefsel.',
        eigenschappen: ['Kleine footprint', 'Stedelijk', 'Intensief ruimtegebruik'],
        ambitieScores: _scores(55, 65, 50, 72, 75),
      },
      {
        id:           'dubbeldeks',
        naam:         'Dubbeldeks type',
        afbeelding:   _IMG.v3,
        afbeelding_floorplan:   _IMG_floorplan.v3,
        lagen:        3,
        bvo:          2900,
        footprint:    1050,
        bouwkosten:   7250000,
        tco:          15950000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Middel',
        beschrijving: 'Driebouwlaags met groot overdekt programma op de begane grond. Combineert intensief grondgebruik met aangename schaalverhouding.',
        eigenschappen: ['3 lagen', 'Overdekte plint', 'Stadsschool'],
        ambitieScores: _scores(62, 68, 58, 75, 72),
      },
      {
        id:           'lprofiel',
        naam:         'L-profiel type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        3,
        bvo:          3000,
        footprint:    1200,
        bouwkosten:   7500000,
        tco:          16500000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Middel',
        beschrijving: 'L-vormige opzet van drie bouwlagen met een half-open binnentuin. Creëert een gedeeltelijk beschut buiten­klimaat voor de school.',
        eigenschappen: ['L-vorm', 'Half-open hof', 'Gelede gevel'],
        ambitieScores: _scores(68, 63, 62, 78, 68),
      },
    ],
  },

  // ── Groep 3: Paviljoen (2 opties) ─────────────────────────────────────────
  {
    id:          'paviljoen',
    naam:        'Paviljoen',
    kleur:       '#F97316',
    beschrijving: 'Losstaande of licht verbonden volumes verspreid over het kavel. Maximale natuurverbinding, informele sfeer en uitbreidbaar in de toekomst.',
    opties: [
      {
        id:           'paviljon',
        naam:         'Paviljoen type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        1,
        bvo:          3600,
        footprint:    3600,
        bouwkosten:   9000000,
        tco:          19800000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Losse paviljoens verbonden door overdekte passages. Maximale daglicht en buitenbeleving, organisch te groeien.',
        eigenschappen: ['Licht & lucht', 'Uitbreidbaar', 'Informele sfeer'],
        ambitieScores: _scores(85, 85, 90, 60, 70),
      },
      {
        id:           'cluster-paviljoen',
        naam:         'Cluster-paviljoen type',
        afbeelding:   _IMG.v3,
        afbeelding_floorplan:   _IMG_floorplan.v3,
        lagen:        1,
        bvo:          3200,
        footprint:    3200,
        bouwkosten:   8000000,
        tco:          17600000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Geclusterde paviljoens die samen een beschut binnendomein vormen. Combinatie van beslotenheid en openheid.',
        eigenschappen: ['Beschut domein', 'Groepsgevoel', 'Natuurlijk licht'],
        ambitieScores: _scores(82, 80, 85, 65, 68),
      },
    ],
  },

  // ── Groep 4: Hybride (6 opties) ───────────────────────────────────────────
  {
    id:          'hybride',
    naam:        'Hybride',
    kleur:       '#6366F1',
    beschrijving: "Combinaties van twee of meer typologieën op één kavel. Geschikt voor complexe programma's of kavels met meerdere randcondities.",
    opties: [
      {
        id:           'compact-hof',
        naam:         'Compact-hof type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        2,
        bvo:          2700,
        footprint:    1600,
        bouwkosten:   6750000,
        tco:          14850000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Middel',
        beschrijving: 'Compacte massa met een kleine open binnenhof. Combineert de efficiëntie van het compact type met de beschutting van het hoftype.',
        eigenschappen: ['Compact + hof', 'Beschut plein', 'Efficiënt'],
        ambitieScores: _scores(70, 62, 62, 80, 66),
      },
      {
        id:           'lineair-toren',
        naam:         'Lineair-toren type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        3,
        bvo:          3000,
        footprint:    1100,
        bouwkosten:   7500000,
        tco:          16500000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Middel',
        beschrijving: 'Lange lage vleugel met een verticaal accent. Oriënteert zich op twee windrichtingen en markeert de entree.',
        eigenschappen: ['Oriënterend accent', 'Dubbele oriëntatie', 'Herkenbaar'],
        ambitieScores: _scores(72, 65, 63, 73, 70),
      },
      {
        id:           'split-niveau',
        naam:         'Split-niveau type',
        afbeelding:   _IMG.v3,
        afbeelding_floorplan:   _IMG_floorplan.v3,
        lagen:        3,
        bvo:          2900,
        footprint:    1250,
        bouwkosten:   7250000,
        tco:          15950000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Laag',
        beschrijving: 'Verdiepingsvloeren op wisselende niveaus creëren een dynamisch interieur. Mezzanines verbinden boven- en benedenwereld visueel.',
        eigenschappen: ['Mezzanines', 'Dynamisch interieur', 'Visuele verbinding'],
        ambitieScores: _scores(73, 62, 68, 70, 72),
      },
      {
        id:           'atrium',
        naam:         'Atrium type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        3,
        bvo:          3300,
        footprint:    1350,
        bouwkosten:   8250000,
        tco:          18150000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Centraal overkapt atrium als hart van de school. Alle verkeersstromen komen samen; maximale sociale controle en ontmoeting.',
        eigenschappen: ['Centraal atrium', 'Overzicht', 'Sociaal hart'],
        ambitieScores: _scores(75, 72, 75, 82, 73),
      },
      {
        id:           'gang-model',
        naam:         'Gang-model type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        2,
        bvo:          2600,
        footprint:    1500,
        bouwkosten:   6500000,
        tco:          14300000,
        duurzaamheid: 'Laag',
        maakbaarheid: 'Hoog',
        beschrijving: 'Klassiek gangmodel met lokalen aan weerszijden. Eenvoudig te realiseren en te beheren, herkenbaar voor gebruikers.',
        eigenschappen: ['Vertrouwd model', 'Eenvoudig beheer', 'Snel te bouwen'],
        ambitieScores: _scores(60, 52, 52, 72, 60),
      },
      {
        id:           'vleugel',
        naam:         'Vleugel type',
        afbeelding:   _IMG.v3,
        afbeelding_floorplan:   _IMG_floorplan.v3,
        lagen:        2,
        bvo:          3200,
        footprint:    1900,
        bouwkosten:   8000000,
        tco:          17600000,
        duurzaamheid: 'Middel',
        maakbaarheid: 'Middel',
        beschrijving: 'Twee of drie vleugels uitgewaaierd vanuit een centrale kern. Scheidt leeftijdsgroepen ruimtelijk terwijl de kern gedeeld blijft.',
        eigenschappen: ['Gescheiden vleugels', 'Gedeeld centrum', 'Herkenbare structuur'],
        ambitieScores: _scores(73, 67, 70, 75, 68),
      },
    ],
  },

  // ── Groep 5: Innovatief & Adaptief (5 opties) ─────────────────────────────
  {
    id:          'innovatief',
    naam:        'Innovatief',
    kleur:       '#059669',
    beschrijving: 'Toekomstgerichte schooltypologieën met nadruk op flexibiliteit, circulariteit en technologische integratie. Hogere investering, lagere TCO.',
    opties: [
      {
        id:           'modulair',
        naam:         'Modulair type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        2,
        bvo:          2800,
        footprint:    1600,
        bouwkosten:   7000000,
        tco:          13700000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Hoog',
        beschrijving: 'Opgebouwd uit gestandaardiseerde bouwmodules. Snel te plaatsen, eenvoudig uit te breiden of te reconfigureren bij wijzigende leerlingaantallen.',
        eigenschappen: ['Snel plaatsbaar', 'Uitbreidbaar', 'Prefab'],
        ambitieScores: _scores(72, 78, 92, 68, 78),
      },
      {
        id:           'transformeerbaar',
        naam:         'Transformeerbaar type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        2,
        bvo:          3000,
        footprint:    1700,
        bouwkosten:   7500000,
        tco:          14000000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Draagstructuur en gevels zijn los van de indelingswanden. Het gebouw past zich aan nieuwe onderwijsconcepten aan zonder sloop.',
        eigenschappen: ['Vrije indeelbaarheid', 'Toekomstbestendig', 'Lage sloopkosten'],
        ambitieScores: _scores(74, 80, 95, 70, 76),
      },
      {
        id:           'circulair',
        naam:         'Circulair type',
        afbeelding:   _IMG.v3,
        afbeelding_floorplan:   _IMG_floorplan.v3,
        lagen:        2,
        bvo:          2900,
        footprint:    1650,
        bouwkosten:   7800000,
        tco:          13200000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Laag',
        beschrijving: 'Volledig circulair ontworpen: biobased materialen, losmaakbare verbindingen en materialenpaspoort. Restwaarde na levensduur maximaal.',
        eigenschappen: ['Biobased', 'Losmaakbaar', 'Materialenpaspoort'],
        ambitieScores: _scores(75, 95, 80, 68, 72),
      },
      {
        id:           'plugin',
        naam:         'Plug-in type',
        afbeelding:   _IMG.v1,
        afbeelding_floorplan:   _IMG_floorplan.v1,
        lagen:        2,
        bvo:          2600,
        footprint:    1400,
        bouwkosten:   6500000,
        tco:          13500000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Primaire draagstructuur met instelbare "plug-in" units voor bijzondere functies. Functiewisselingen zijn mogelijk zonder bouwvergunning.',
        eigenschappen: ['Plug-in units', 'Flexibele functies', 'Minimale vergunningen'],
        ambitieScores: _scores(70, 77, 90, 72, 82),
      },
      {
        id:           'smart',
        naam:         'Smart school type',
        afbeelding:   _IMG.v2,
        afbeelding_floorplan:   _IMG_floorplan.v2,
        lagen:        2,
        bvo:          2700,
        footprint:    1500,
        bouwkosten:   7200000,
        tco:          12900000,
        duurzaamheid: 'Hoog',
        maakbaarheid: 'Middel',
        beschrijving: 'Gebouwautomatisering voor energie, luchtkwaliteit, licht en gebruik. Data-gedreven beheer verlaagt structureel de exploitatiekosten.',
        eigenschappen: ['IoT-integratie', 'Data-gestuurd beheer', 'Lage exploitatie'],
        ambitieScores: _scores(82, 82, 75, 75, 95),
      },
    ],
  },

];

// ── Platte lookup-array ────────────────────────────────────────────────────────
window.GEBOUW_ALLE_OPTIES = window.GEBOUW_OPTIES_GROUPS.flatMap(g => g.opties);

// ── Hulpfunctie: zoek optie op id ─────────────────────────────────────────────
window.getGebouwOptie = id => window.GEBOUW_ALLE_OPTIES.find(o => o.id === id) || null;
